### ISSUE TITLE
Please publish it on NPM

### ISSUE THREAD

**Issue by ferlores** [jtangelder/gulp-stripmq#1]
Thanks!!

**Comment by davatron5000** [comment]
:+1: to publishing it on NPM. Dropped it in on a project and I'm as happy as a pig in slop.

**Comment by jtangelder** [comment]
Adding it as an git dependency will also work!

**Comment by jtangelder** [comment]
https://www.npmjs.com/package/gulp-stripmq

**Comment by ferlores** [comment]
Yes, it works as a git dependency and this is what I'm doing now. Although, there are many advantages using it though NPM. If you are not planning to add support for that then probably I will use another module for this.
Thanks
F

**Comment by jtangelder** [comment]
It's on NPM as i mentioned! :smile:
